### ISSUE TITLE
Visible Sensitive Information

### ISSUE THREAD

**Issue by dyl10s** [adamchlebek/GV-ESports-Louie#2]
**Describe the bug**
This bug was discovered when reviewing this indicate source code. I wanted to inform not only the lead developer "Adam Chlebek" but also the community as an example of what not to do.

**To Reproduce**
Open sqlConnector.cs
Scroll to line 42
View the credentials

**Expected behavior**
Do not show passwords on public github repos

**Screenshots**
![image](https://user-images.githubusercontent.com/12243691/56477335-890eab00-6472-11e9-972c-dd69698479ef.png)

**Additional context**
I think the valid and or reasonable approach to this solution would be to not post the password and username on a public github repo.

I hope this helps!

**Comment by adamchlebek** [comment]
Thank you for the reported issue and the fix. Much appreciated dyl10s!
